/*
 * ProductManagerWorkAreaJPanel.java
 *
 * Created on October 3, 2008, 8:06 AM
 */
package ui.CustomerRole;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import ui.AdminRole.AdminWorkAreaJPanel;
import image_slide.*;
import java.util.ArrayList;
import java.util.List;
import model.Consignment;
import model.OrderItems;
import model.ProductCatalog;
import model.User;
import ui.SupplierRole.SupplierLoginJPanel;







/**
 *
 * @author Rushabh
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {


    private JPanel userProcessContainer;
    User loggedInUser;
    ProductCatalog cart= new ProductCatalog();
    List<OrderItems> orderItemList= new ArrayList<OrderItems>();
    //ImageSlide imageSlide;
    /** Creates new form ProductManagerWorkAreaJPanel */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, User loggedInUser) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.loggedInUser=loggedInUser;
        
        //imageSlide=new ImageSlide();
            imageSlide1.addImage(new ImageIcon("C:/javaprojects/Sanaye_Nikhil_002926665/final_project/project_images/1.png"));
            imageSlide1.addImage(new ImageIcon("C:/javaprojects/Sanaye_Nikhil_002926665/final_project/project_images/2.jpg"));
            imageSlide1.addImage(new ImageIcon("C:/javaprojects/Sanaye_Nikhil_002926665/final_project/project_images/3.jpg"));
            imageSlide1.addImage(new ImageIcon("C:/javaprojects/Sanaye_Nikhil_002926665/final_project/project_images/4.jpg"));
            //C:\javaprojects\Sanaye_Nikhil_002926665\final_project\project_images
        //imageSlide.addImage(new ImageIcon(getClass().getResource("C:/javaprojects/Sanaye_Nikhil_002926665/final_project/src/bannerImage/1.png")));
        //imageSlide.addImage(new ImageIcon(getClass().getResource("C:/javaprojects/Sanaye_Nikhil_002926665/final_project/src/bannerImage/1.png")));
        
        //imageSlide.addImage(new ImageIcon(getClass().getResource("/img/3.jpg")));
        //imageSlide.addImage(new ImageIcon(getClass().getResource("/img/4.jpg")));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jPanelController = new javax.swing.JPanel();
        btnBrowseProducts = new javax.swing.JButton();
        btnCartItems = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        btnMyOrders = new javax.swing.JButton();
        btnViewPromotions = new javax.swing.JButton();
        btnMyOrders1 = new javax.swing.JButton();
        customerUserProcessContainer = new javax.swing.JPanel();
        firstjPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        imageSlide1 = new image_slide.ImageSlide();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 0, 0));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logoPleaseBuySmall.png"))); // NOI18N
        lblTitle.setText("Welcome Dear Customer!");
        lblTitle.setIconTextGap(20);

        jPanelController.setBackground(new java.awt.Color(153, 153, 153));

        btnBrowseProducts.setText("Browse Products");
        btnBrowseProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseProductsActionPerformed(evt);
            }
        });

        btnCartItems.setText("Cart Items");
        btnCartItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartItemsActionPerformed(evt);
            }
        });

        btnMyProfile.setText("My Profile");
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileActionPerformed(evt);
            }
        });

        btnMyOrders.setText("My orders");
        btnMyOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyOrdersActionPerformed(evt);
            }
        });

        btnViewPromotions.setText("View Promotions");
        btnViewPromotions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPromotionsActionPerformed(evt);
            }
        });

        btnMyOrders1.setText("Complaints?");
        btnMyOrders1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyOrders1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControllerLayout = new javax.swing.GroupLayout(jPanelController);
        jPanelController.setLayout(jPanelControllerLayout);
        jPanelControllerLayout.setHorizontalGroup(
            jPanelControllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControllerLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanelControllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBrowseProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCartItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMyProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMyOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPromotions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMyOrders1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelControllerLayout.setVerticalGroup(
            jPanelControllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControllerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnViewPromotions, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBrowseProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCartItems, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMyOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMyOrders1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerUserProcessContainer.setBackground(new java.awt.Color(255, 204, 204));
        customerUserProcessContainer.setLayout(new java.awt.CardLayout());

        firstjPanel.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setText("1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setText("3");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("4");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstjPanelLayout = new javax.swing.GroupLayout(firstjPanel);
        firstjPanel.setLayout(firstjPanelLayout);
        firstjPanelLayout.setHorizontalGroup(
            firstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstjPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton4)
                .addGap(34, 34, 34)
                .addComponent(jButton5)
                .addGap(33, 33, 33)
                .addComponent(jButton9)
                .addGap(26, 26, 26)
                .addComponent(jButton10)
                .addContainerGap(293, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageSlide1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        firstjPanelLayout.setVerticalGroup(
            firstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstjPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(firstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageSlide1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        customerUserProcessContainer.add(firstjPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanelController, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(customerUserProcessContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelController, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerUserProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseProductsActionPerformed
        // TODO add your handling code here:
        
        customerUserProcessContainer.removeAll();
        customerUserProcessContainer.add(new BrowseProductsJPanel(customerUserProcessContainer,orderItemList));
        customerUserProcessContainer.repaint();
        customerUserProcessContainer.revalidate();
    }//GEN-LAST:event_btnBrowseProductsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         imageSlide1.showImage(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        imageSlide1.showImage(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCartItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartItemsActionPerformed
        // TODO add your handling code here:\
        ManageCartJPanel mcjp = new ManageCartJPanel(customerUserProcessContainer, loggedInUser, orderItemList);
        customerUserProcessContainer.add("ManageCartJPanel", mcjp);
        CardLayout layout = (CardLayout)customerUserProcessContainer.getLayout();
        layout.next(customerUserProcessContainer);
        
    }//GEN-LAST:event_btnCartItemsActionPerformed

    private void btnMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileActionPerformed
        // TODO add your handling code here:
        ViewProfileDetailJPanel vpdjp = new ViewProfileDetailJPanel(userProcessContainer, loggedInUser.getMailId());
        customerUserProcessContainer.add("ViewProfiletDetailJPanel", vpdjp);
        CardLayout layout = (CardLayout)customerUserProcessContainer.getLayout();
        layout.next(customerUserProcessContainer);
    }//GEN-LAST:event_btnMyProfileActionPerformed

    private void btnMyOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyOrdersActionPerformed
        // TODO add your handling code here:
        MyOrdersJPanel mojp = new MyOrdersJPanel(userProcessContainer, loggedInUser);
        customerUserProcessContainer.add("MyOrdersJPanel", mojp);
        CardLayout layout = (CardLayout)customerUserProcessContainer.getLayout();
        layout.next(customerUserProcessContainer);
    }//GEN-LAST:event_btnMyOrdersActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        imageSlide1.showImage(2);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        imageSlide1.showImage(3);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnViewPromotionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPromotionsActionPerformed
        // TODO add your handling code here:
        //firstjPanel vpdjp = new firstjPanel(userProcessContainer, userName);
        customerUserProcessContainer.add(firstjPanel);
        CardLayout layout = (CardLayout)customerUserProcessContainer.getLayout();
        layout.next(customerUserProcessContainer);
    }//GEN-LAST:event_btnViewPromotionsActionPerformed

    private void btnMyOrders1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyOrders1ActionPerformed
        // TODO add your handling code here:
        ComplaintRefundReturnJPanel rrjp = new ComplaintRefundReturnJPanel(customerUserProcessContainer, loggedInUser);
        customerUserProcessContainer.add("RefundReturnJPanel", rrjp);
        CardLayout layout = (CardLayout)customerUserProcessContainer.getLayout();
        layout.next(customerUserProcessContainer);
    }//GEN-LAST:event_btnMyOrders1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseProducts;
    private javax.swing.JButton btnCartItems;
    private javax.swing.JButton btnMyOrders;
    private javax.swing.JButton btnMyOrders1;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnViewPromotions;
    private javax.swing.JPanel customerUserProcessContainer;
    private javax.swing.JPanel firstjPanel;
    private image_slide.ImageSlide imageSlide1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanelController;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
