package ui.Doctor;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.SystemCatalog;
import model.Person;

/**
 *
 * @author  Mihir Mehta / Hechen Gao
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {
  
    private JPanel userProcessContainer;
    private SystemCatalog personCatalog;
    public DoctorWorkAreaJPanel(JPanel userProcessContainer,SystemCatalog personCatalog) {
        
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.personCatalog= personCatalog;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManagePatientData = new javax.swing.JButton();
        jDoctorWorkArea = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(650, 600));

        btnManagePatientData.setText("Manage Patient Data >>");
        btnManagePatientData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientDataActionPerformed(evt);
            }
        });

        jDoctorWorkArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jDoctorWorkArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDoctorWorkArea.setText("Doctor's Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDoctorWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnManagePatientData)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jDoctorWorkArea)
                .addGap(66, 66, 66)
                .addComponent(btnManagePatientData)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePatientDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientDataActionPerformed
    ManagePatientJPanel mpjp = new ManagePatientJPanel(userProcessContainer, personCatalog);
    userProcessContainer.add("ManagePatientJPanel", mpjp);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePatientDataActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManagePatientData;
    private javax.swing.JLabel jDoctorWorkArea;
    // End of variables declaration//GEN-END:variables
    
}
